### ISSUE TITLE
TOPページのでざいん

### ISSUE THREAD

**Issue by yuuuuuumi** [annp-jp/tucho#47]

**Comment by katsumata-ryo** [comment]
早速使ってくれたのねー！ありがとー！
一般的な使い方だけど

Backlog => ブレスト状態のタスク
Ready => やることは決定でまだ作業前のもの（タスクの控え選手？）
In Progress => 作業中（基本的にここには一個程度しか自分のタスクが入らないようにする）
done => 完全に終了したタスク

って感じになるので、作業開始になったらInProgressに移してみてくださいー。

**Comment by yuuuuuumi** [comment]
なるほどなるほど！了解で〜す！！

**Comment by yuuuuuumi** [comment]
![top](https://cloud.githubusercontent.com/assets/16576268/12652584/c7cc1656-c62e-11e5-90f6-52219b504a24.jpg)
お待たせいたしました！どシンプルですがデザイン作ってみました〜！
bootstrapとかコーディングとかあんまり複雑になりすぎないような感じで作っております。
ボタンとかリンクのところにはこの前教えてもらったアイコンのcss?使っても良いのではないかなっと思っています。
取り急ぎ作った感じなので、ご希望のイメージとかあったら言ってください！
今忙しい時期だと思うのでご確認は時間空いた時にゆったり気が向いた時にとかで全然大丈夫ですので☆よろしくお願いします〜

**Comment by katsumata-ryo** [comment]
ありがとー！

すでに自分にブレが生じていて、現時点で

* アプリの名前を変えそう
* キャッチフレーズをちゃんとに練り直しそう

っていうのがあるので相談させてください。
次回のMTGまでに質問とか考えておきます！  
ちなみにもう体調はよさ？ハングアウトを土日にどうかなと思っているのだけどー予定と体調はどうだろう。

**Comment by katsumata-ryo** [comment]
質問メモ（口頭で聞く）

* 大きな流れとしてはすごく良い
* タイトルフォントの意図
* 使える色のパターンのイメージ
    * 重要度、リンク色、ポイント色、カラーパターン
* イメージ作成までの経緯
    * イメージしたものの共有
* 画像の場所の確認
    * 線とチョビ三角さん
    * キャッチフレーズ
    * 右上のログイン
* 下のメニュー
    * 今メニューあるけど、もしかしたらTOPにはいらないのかもしれない。ログインしてないし。
* 下層ページの感じ
    * メニュー。
* 極力古田さんに動かないでもらってコーディングしていく方法の相談

**Comment by katsumata-ryo** [comment]
トップページ情報量の個人用メモ

* 扉ページ
    * twitter: https://twitter.com/?lang=ja
        * 新規登録、ログイン
    * https://esa.io/
        * ドキュメント、アプリについての説明ページ
        * サインアップ、トライアル
    * http://www.cchan.tv/
        * 毛色が違いすぎて参考にならない
        * 会員入力が必要なくても使えるサービスゆえ
    * https://www.tenpu.me/
        * 会員登録が必要ないサービスの場合
    * https://prottapp.com/ja/
        * 新着情報の出し方
        * フリーミアム
    * http://joinus30.com/
        * やっぱりアプリはいるなという印象

**Comment by yuuuuuumi** [comment]
おお！早速確認ありがとうございます〜＾＾！！
体調はもう大丈夫です♪ハングアウト明日なら大丈夫です〜！
ただ、私が実家に里帰る予定が早まりまして、引っ越し準備とかでその後の作業ができるや否やという感じになってしまて＞＜それも含めハングアウトで相談させてくださいまし！！

**Comment by katsumata-ryo** [comment]
@yuuuuuumi
したら土曜日のどこかの時間で話しますかー！
夜でも大丈夫かなー？昼の方がいい場合は時間を指定してもらえるとー！

(ただ、最終出社日で今帰ってきたからそこそこ早い時間は夢の中かもしれない( ˘ω˘) )

**Comment by yuuuuuumi** [comment]
NF最終日お疲れさまでした〜〜＞＜！！オールだったのですねww
夜で大丈夫です^^17時or18時あたりどうです？
お返事は夢から目覚めてからで大丈夫ですので☆

**Comment by katsumata-ryo** [comment]
@yuuuuuumi
18時からにしよー！直前に#developのslackチャネルかられんらくするねー

**Comment by katsumata-ryo** [comment]
サンクス！
